title: "UTMStack Lab — Guide de déploiement"
description: "UTMStack v11.2.8 Community Edition — Guide de déploiement pour lab PME Suisse 🇨🇭"
url: "https://doit4everyone.github.io"
baseurl: "/utmstack-lab"
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
